export const UI_PLAYBACK_MODE = 'UI_PLAYBACK_MODE'
export const UI_LIST_PREVIEW_MODE = 'UI_LIST_PREVIEW_MODE'

export const USER_PLAYING_MODE = 'USER_PLAYING_MODE'
export const USER_RESTING_MODE = 'USER_RESTING_MODE'
