export const UI_PLAYBACK_MODE = 'UI_PLAYBACK_MODE'
export const UI_LIST_PREVIEW_MODE = 'UI_LIST_PREVIEW_MODE'

export const USER_PLAYING_MODE = 'USER_PLAYING_MODE'
export const USER_RESTING_MODE = 'USER_RESTING_MODE'

export const SORT_BY_TIMESTAMP_MODE = 'SORT_BY_TIMESTAMP_MODE'
export const SORT_BY_PLAYLIST_MODE = 'SORT_BY_PLAYLIST_MODE'
